---
# Fedora setup for GitKraken

- name: Detect broken setup
  stat:
    path: "{{ gitkraken_install_path }}/gitkraken"
  tags:
    - gitkraken
  register: gitkraken_broken_setup

- name: Remove broken setup
  file:
    path: "{{ gitkraken_install_path }}"
    state: absent
  tags:
    - gitkraken
  become: true
  when: gitkraken_broken_setup.stat.isdir is defined and gitkraken_broken_setup.stat.isdir

- name: Check that GitKraken is installed
  stat:
    path: "{{ gitkraken_install_path }}"
  tags:
    - gitkraken
  register: gitkraken_dir

- name: Download GitKraken
  get_url: 
    url: "{{ gitkraken_download_url }}"
    dest: "{{ gitkraken_download_path }}"
  tags:
    - download
    - gitkraken
  when: gitkraken_dir.stat.exists == False

- name: Unpack GitKraken
  unarchive:
    src: "{{ gitkraken_download_path }}"
    dest: "/tmp/"
    remote_src: yes
  tags:
    - gitkraken
    - unarchive
  register: unpacked_gitkraken
  when: gitkraken_dir.stat.exists == False

- name: Install GitKraken
  command: "mv /tmp/gitkraken {{ gitkraken_install_path }}"
  args:
    creates: "{{ gitkraken_install_path }}"
  tags:
    - gitkraken
  become: yes
  when: gitkraken_dir.stat.exists == False

- name: Clean up
  file:
    path: /tmp/gitkraken
    state: absent
  tags:
    - gitkraken
  when: unpacked_gitkraken|succeeded

- name: Create desktop entry
  template:
    src: gitkraken.desktop
    dest: /usr/share/applications/gitkraken.desktop
  tags:
    - gitkraken
    - desktop
  become: true

- name: Install desktop icon
  copy:
    src: gitkraken.png
    dest: /usr/share/icons/hicolor/512x512/apps/gitkraken.png
  tags:
    - gitkraken
    - gtk
    - icons
    - desktop
  become: true
  notify: "refresh GTK icon cache"

- name: Install GitKraken to path
  file:
    state: link
    src: "{{ gitkraken_install_path }}/gitkraken"
    dest: "/usr/local/bin/gitkraken"
  tags:
    - gitkraken
    - path
  become: true

- name: Install Nautilus-Extension
  copy:
    src: open-gitkraken.py
    dest: /usr/share/nautilus-python/extensions/open-gitkraken.py
  tags:
    - gitkraken
    - python
    - nautilus
    - nautilus-python
    - nautlius-python-extension
  become: true
  notify: "Nautilus python extension notification"

- name: Increase inotify count
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    sysctl_set: yes
    state: present
    reload: yes
  become: true
