---
# tasks file for default-tooling

- name: Install default packages
  dnf: 
    name: "{{ packages | union(extended_packages | default([])) | selectattr('dnf', 'defined') | map(attribute='dnf') | list }}"
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true

- name: Install default flatpaks
  flatpak: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages | union(extended_packages | default([])) | selectattr('flatpak', 'defined') | map(attribute='flatpak') | list }}"
  tags:
    - flatpak
    - download
    - packages
  become: true

- name: Check if compat-ffmpeg package is installed
  package:
    name: compat-ffmpeg28
    state: latest
  check_mode: true
  ignore_errors: true
  register: ffmpeg28_check

- name: Workaround for compat-ffmpeg
  dnf:
    name: "compat-ffmpeg28"
    state: latest
  when:
    - ffmpeg28_check is changed

- name: Setup toolbox-powerline in bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      # Toolbox-Powerline
      # Load OS information and register variable for powerline
      # to display special segment if user is within a container
      source /etc/os-release
      if [ "$VARIANT_ID" = "container" ]; then
        export POWERLINE_VIRTUAL_ENV_NAME=toolbox
      fi
  tags:
    - bash
