---
# tasks file for lenovo carbon 6th gen patch cpu-throttling

- name: Fix CPU Throttling Issues
  block:
  - name: Enable COPR
    command: "dnf copr enable -y abn/throttled"
    args:
      creates: "_copr:copr.fedorainfracloud.org:abn:throttled.repo"
      warn: false
    tags:
      - dnf
      - copr
    become: true

  - name: Enable systemd service
    systemd:
      name: throttled.service
      enabled: yes
      state: started
      daemon_reload: yes
    become: true

  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version is version('32', '>')
    - hardware_thinkpad_x1_carbon_6th_cpu_throttling_fix is defined
    - hardware_thinkpad_x1_carbon_6th_cpu_throttling_fix
