---
# tasks file for lenovo carbon 6th gen patch cpu-throttling

- name: Install hardware monitoring tools
  dnf:
    name:
      - s-tui
      - powertop
      - tlp
    state: present
  become: true
  tags:
    - dnf
    - packages
    - download

- name: Fix TrackPoint and TrackPad conflict issue
  copy:
    src: psmouse.conf
    dest: /etc/modprobe.d/psmouse.conf
    owner: root
    group: root
    mode: 0600
  become: true
  tags:
    - modules
  when:
    - hardware_thinkpad_x1_carbon_6th_psmouse_fix is defined
    - hardware_thinkpad_x1_carbon_6th_psmouse_fix
