---
# tasks file for Flathub

- name: Install flatpak
  dnf:
    name: "flatpak"
    state: present
  tags:
    - flatpak
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub-full
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
  when:
    - ansible_version.major is version('2', '>=')
    - ansible_version.minor is version('6', '>=')
  become: true
