---
# tasks file for atom

- name: Import GPG key
  rpm_key:
    state: present
    key: "https://packagecloud.io/AtomEditor/atom/gpgkey"
  tags:
    - atom
    - dnf
    - gpg-key
    - download
  become: true

- name: Add official repository
  yum_repository:
    state: present
    name: "{{ atom_reponame }}"
    description: Official repository for Atom
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
  tags:
    - atom
    - dnf
    - gpg-key
  register: atom_repo
  become: true

- name: update repo cache for the new repo
  command: "dnf -q makecache -y \"--disablerepo=*\" \"--enablerepo={{ atom_reponame }}\""
  when:
    - atom_repo is changed

- name: Install Atom
  dnf:
    name: atom
    state: present
  tags:
    - atom
    - dnf
    - packages
  become: true

- name: Install Nautilus-Extension
  copy:
    src: open-atom.py
    dest: /usr/share/nautilus-python/extensions/open-atom.py
  tags:
    - atom
    - python
    - nautilus
    - nautilus-python
    - nautlius-python-extension
  become: true
