---

- name: Install development utilites
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - '@Development Tools'
    - '@Development Libraries'
    - golang-bin
    - python3-spyder
    - npm
    - ShellCheck
  tags:
    - dnf
    - download
    - packages
  become: true

- name: Install development utilities (flatpak)
  flatpak:
    name: "{{ item }}"
  with_items:
    - com.github.alecaddd.sequeler
    - com.getpostman.Postman
  tags:
    - flatpak
    - download
    - packages
  become: true
