---

- name: Install container utilites
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - podman
    - podman-docker
    - podman-compose
    - docker-compose
  tags:
    - dnf
    - download
    - packages
  become: true
