---

- name: Install container utilites
  dnf: 
    name:
      - podman
      - podman-docker
      - podman-compose
      - docker-compose
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true
