---

- name: Install system base packages
  ansible.builtin.dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server
  tags:
    - dnf
    - download
    - packages
  become: true
