---
# tasks file for automated-updates

- name: Install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present
  tags:
    - dnf
    - automated-updates
  notify: 
    - restart dnf-automatic
  become: true

- name: Set automated install setting
  ini_file:
    path: /etc/dnf/automatic.conf
    section: commands
    option: apply_updates
    value: "{{ automated_updates_enabled }}"
    backup: yes
  tags:
    - automated-updates
    - dnf
    - config
  become: true
